# Generated by Django 3.2.8 on 2021-11-05 10:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('date_searched', models.DateTimeField(default=django.utils.timezone.now)),
                ('metric', models.BooleanField(default=False)),
            ],
        ),
    ]
